Repository hashicorp/terraform-provider-dns, pull requests merged in 2018-05, with the labels that each got.

#39 checking type on Get*Val(record interface{}) like functions
  dns/provider.go
Labels: bug

#36 Validate TSIG key name and resource zone/record names
  dns/config.go
  dns/resource_dns_a_record_set.go
  dns/resource_dns_a_record_set_test.go
  dns/resource_dns_aaaa_record_set.go
  dns/resource_dns_aaaa_record_set_test.go
  dns/resource_dns_cname_record.go
  dns/resource_dns_cname_record_test.go
  dns/resource_dns_ns_record_set.go
  dns/resource_dns_ns_record_set_test.go
  dns/resource_dns_ptr_record.go
  dns/resource_dns_ptr_record_test.go
  dns/validators.go
  dns/validators_test.go
Labels: bug, crash

#43 Fixes failing tests and updated readme.md acceptance test instructions
  README.md
  dns/data_dns_a_record_set_test.go
  dns/data_dns_aaaa_record_set_test.go
  dns/data_dns_cname_record_set_test.go
  dns/data_dns_ns_record_set_test.go
  dns/data_dns_ptr_record_set_test.go
  dns/data_dns_txt_record_set_test.go
  dns/resource_dns_a_record_set_test.go
  dns/resource_dns_aaaa_record_set_test.go
  dns/resource_dns_cname_record_test.go
  dns/resource_dns_ns_record_set_test.go
  dns/resource_dns_ptr_record_test.go
Labels: bug, documentation

#44 Add acceptance tests to travis
  .travis.yml
Labels: enhancement
