Repository hashicorp/terraform-provider-dns, pull requests merged in 2019-01, with the labels that each got.

#73 [AUTOMATED] Upgrade to Go 1.11
  .travis.yml
  README.md
  dns/data_dns_a_record_set.go
  dns/data_dns_aaaa_record_set.go
  dns/data_dns_cname_record_set.go
  dns/data_dns_ns_record_set.go
  dns/data_dns_ptr_record_set.go
  dns/data_dns_txt_record_set.go
  dns/provider.go
  dns/resource_dns_a_record_set.go
  dns/resource_dns_aaaa_record_set.go
  dns/resource_dns_cname_record.go
  dns/resource_dns_ns_record_set.go
  dns/resource_dns_ptr_record.go
Labels: size/M

#69 Allow creating apex records
  dns/provider.go
  dns/provider_test.go
  dns/resource_dns_a_record_set.go
  dns/resource_dns_a_record_set_test.go
  dns/resource_dns_aaaa_record_set.go
  dns/resource_dns_aaaa_record_set_test.go
  dns/resource_dns_cname_record.go
  dns/resource_dns_cname_record_test.go
  dns/resource_dns_ns_record_set.go
  dns/resource_dns_ns_record_set_test.go
  dns/resource_dns_ptr_record.go
  dns/resource_dns_ptr_record_test.go
  dns/validators.go
  dns/validators_test.go
  website/docs/r/dns_a_record_set.html.markdown
  website/docs/r/dns_aaaa_record_set.html.markdown
  website/docs/r/dns_ptr_record.html.markdown
Labels: documentation, size/XL

#72 TXT record resource
  dns/provider.go
  dns/resource_dns_txt_record_set.go
  dns/resource_dns_txt_record_set_test.go
  website/dns.erb
  website/docs/r/dns_txt_record_set.html.markdown
Labels: documentation, size/XL

#71 MX record resource and datasource
  dns/data_dns_mx_record_set.go
  dns/data_dns_mx_record_set_test.go
  dns/provider.go
  dns/resource_dns_mx_record_set.go
  dns/resource_dns_mx_record_set_test.go
  website/dns.erb
  website/docs/d/dns_mx_record_set.html.markdown
  website/docs/r/dns_mx_record_set.html.markdown
Labels: documentation, new-data-source, new-resource, size/XL
