Repository hashicorp/terraform-provider-dns, pull requests merged in 2021-07, with the labels that each got.

#122 CI: GitHub Actions
  .github/workflows/test.yml
  .travis.yml
  internal/provider/data_dns_txt_record_set_test.go
Labels: size/M

#155 Update dns and krb5 dependencies
  go.mod
  go.sum
Labels: dependencies, size/XS

#158 tests: Switch to hashicorptest.com DNS records for testing
  internal/provider/data_dns_a_record_set_test.go
  internal/provider/data_dns_aaaa_record_set_test.go
  internal/provider/data_dns_cname_record_set_test.go
  internal/provider/data_dns_mx_record_set_test.go
  internal/provider/data_dns_ns_record_set_test.go
  internal/provider/data_dns_srv_record_set_test.go
  internal/provider/data_dns_txt_record_set_test.go
Labels: size/M, tests
