Repository hashicorp/terraform-provider-dns, pull requests merged in 2022-03, with the labels that each got.

#191 GH Action to link incoming issues and pull-requests to the Terraform DevEx Team board
  .github/workflows/add-content-to-project.yml
Labels: size/S

#192 docs: Remove legacy sidebar features
  website/dns.erb
  website/docs/d/dns_a_record_set.html.markdown
  website/docs/d/dns_aaaa_record_set.html.markdown
  website/docs/d/dns_cname_record_set.html.markdown
  website/docs/d/dns_mx_record_set.html.markdown
  website/docs/d/dns_ns_record_set.html.markdown
  website/docs/d/dns_ptr_record_set.html.markdown
  website/docs/d/dns_srv_record_set.html.markdown
  website/docs/d/dns_txt_record_set.html.markdown
  website/docs/index.html.markdown
  website/docs/r/dns_a_record_set.html.markdown
  website/docs/r/dns_aaaa_record_set.html.markdown
  website/docs/r/dns_cname_record.html.markdown
  website/docs/r/dns_mx_record_set.html.markdown
  website/docs/r/dns_ns_record_set.html.markdown
  website/docs/r/dns_ptr_record.html.markdown
  website/docs/r/dns_srv_record_set.html.markdown
  website/docs/r/dns_txt_record_set.html.markdown
Labels: documentation, size/M

#193 Update GH Action 'add-content-to-project' to use 'pull_request_target' to allow access to project secrets
  .github/workflows/add-content-to-project.yml
Labels: size/XS

#194 Update CODEOWNERS with new team name: @hashicorp/terraform-devex
  .github/CODEOWNERS
Labels: size/XS

#199 Bump Go version to 1.16.15, prepare 3.2.2 release
  .go-version
  CHANGELOG.md
  internal/provider/data_dns_txt_record_set_test.go
Labels: size/XS
