Repository hashicorp/terraform-provider-dns, pull requests merged in 2023-11, with the labels that each got.

#372 cdktf: update documentation
  docs/cdktf/python/data-sources/a_record_set.md
  docs/cdktf/python/data-sources/aaaa_record_set.md
  docs/cdktf/python/data-sources/cname_record_set.md
  docs/cdktf/python/data-sources/mx_record_set.md
  docs/cdktf/python/data-sources/ns_record_set.md
  docs/cdktf/python/data-sources/ptr_record_set.md
  docs/cdktf/python/data-sources/srv_record_set.md
  docs/cdktf/python/data-sources/txt_record_set.md
  docs/cdktf/python/index.md
  docs/cdktf/python/resources/a_record_set.md
  docs/cdktf/python/resources/aaaa_record_set.md
  docs/cdktf/python/resources/cname_record.md
  docs/cdktf/python/resources/mx_record_set.md
  docs/cdktf/python/resources/ns_record_set.md
  docs/cdktf/python/resources/ptr_record.md
  docs/cdktf/python/resources/srv_record_set.md
  docs/cdktf/python/resources/txt_record_set.md
  docs/cdktf/typescript/data-sources/a_record_set.md
  docs/cdktf/typescript/data-sources/aaaa_record_set.md
  docs/cdktf/typescript/data-sources/cname_record_set.md
  docs/cdktf/typescript/data-sources/mx_record_set.md
  docs/cdktf/typescript/data-sources/ns_record_set.md
  docs/cdktf/typescript/data-sources/ptr_record_set.md
  docs/cdktf/typescript/data-sources/srv_record_set.md
  docs/cdktf/typescript/data-sources/txt_record_set.md
  docs/cdktf/typescript/index.md
  docs/cdktf/typescript/resources/a_record_set.md
  docs/cdktf/typescript/resources/aaaa_record_set.md
  docs/cdktf/typescript/resources/cname_record.md
  docs/cdktf/typescript/resources/mx_record_set.md
  docs/cdktf/typescript/resources/ns_record_set.md
  docs/cdktf/typescript/resources/ptr_record.md
  docs/cdktf/typescript/resources/srv_record_set.md
  docs/cdktf/typescript/resources/txt_record_set.md
Labels: size/M

#380 .github: Add CI for changie
  .github/workflows/ci-changie.yml
Labels: size/XS

#382 .github: Update workflows to use actions variables
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: size/S

#383 Automatically close associated milestone on release
  .goreleaser.yml
Labels: size/XS
