Repository hashicorp/terraform-provider-dns, pull requests merged in 2023-04, with the labels that each got.

#288 docs: Use default terraform-plugin-docs templates for data sources and resources
  docs/data-sources/a_record_set.md
  docs/data-sources/aaaa_record_set.md
  docs/data-sources/cname_record_set.md
  docs/data-sources/mx_record_set.md
  docs/data-sources/ns_record_set.md
  docs/data-sources/ptr_record_set.md
  docs/data-sources/srv_record_set.md
  docs/data-sources/txt_record_set.md
  docs/resources/a_record_set.md
  docs/resources/aaaa_record_set.md
  docs/resources/cname_record.md
  docs/resources/mx_record_set.md
  docs/resources/ns_record_set.md
  docs/resources/ptr_record.md
  docs/resources/srv_record_set.md
  docs/resources/txt_record_set.md
  examples/data-sources/dns_a_record_set/data-source.tf
  examples/data-sources/dns_aaaa_record_set/data-source.tf
  examples/data-sources/dns_cname_record_set/data-source.tf
  examples/data-sources/dns_mx_record_set/data-source.tf
  examples/data-sources/dns_ns_record_set/data-source.tf
  examples/data-sources/dns_ptr_record_set/data-source.tf
  examples/data-sources/dns_srv_record_set/data-source.tf
  examples/data-sources/dns_txt_record_set/data-source.tf
  examples/resources/dns_a_record_set/import.sh
  examples/resources/dns_a_record_set/resource.tf
  examples/resources/dns_aaaa_record_set/import.sh
  examples/resources/dns_aaaa_record_set/resource.tf
  examples/resources/dns_cname_record/import.sh
  examples/resources/dns_cname_record/resource.tf
  examples/resources/dns_mx_record_set/import.sh
  examples/resources/dns_mx_record_set/resource.tf
  examples/resources/dns_ns_record_set/import.sh
  examples/resources/dns_ns_record_set/resource.tf
  examples/resources/dns_ptr_record/import.sh
  examples/resources/dns_ptr_record/resource.tf
  examples/resources/dns_srv_record_set/import.sh
  examples/resources/dns_srv_record_set/resource.tf
  examples/resources/dns_txt_record_set/import.sh
  examples/resources/dns_txt_record_set/resource.tf
  templates/data-sources/a_record_set.md.tmpl
  templates/data-sources/aaaa_record_set.md.tmpl
  templates/data-sources/cname_record_set.md.tmpl
  templates/data-sources/mx_record_set.md.tmpl
  templates/data-sources/ns_record_set.md.tmpl
  templates/data-sources/ptr_record_set.md.tmpl
  templates/data-sources/srv_record_set.md.tmpl
  templates/data-sources/txt_record_set.md.tmpl
  templates/resources/a_record_set.md.tmpl
  templates/resources/aaaa_record_set.md.tmpl
  templates/resources/cname_record.md.tmpl
  templates/resources/mx_record_set.md.tmpl
  templates/resources/ns_record_set.md.tmpl
  templates/resources/ptr_record.md.tmpl
  templates/resources/srv_record_set.md.tmpl
  templates/resources/txt_record_set.md.tmpl
Labels: size/XL

#291 Correctly handle DNS client configuration
  .changes/unreleased/BUG FIXES-20230419-160433.yaml
  .changes/unreleased/BUG FIXES-20230419-161012.yaml
  internal/provider/config.go
  internal/provider/provider.go
  internal/provider/provider_framework.go
  internal/provider/provider_test.go
Labels: bug, size/M

#294 provider: Test using mux server, prevent mux server errors, and add provider environment variables to descriptions
  .changes/unreleased/BUG FIXES-20230421-143032.yaml
  docs/index.md
  internal/provider/provider.go
  internal/provider/provider_framework.go
  internal/provider/provider_test.go
Labels: bug, size/L

#292 internal/provider: Initial unit testing for provider Configure method
  internal/provider/provider_framework.go
  internal/provider/provider_framework_test.go
Labels: size/XL, technical-debt

#295 internal/provider: Consolidate testing record removal logic
  internal/provider/provider_test.go
  internal/provider/resource_dns_a_record_set_test.go
  internal/provider/resource_dns_aaaa_record_set_test.go
  internal/provider/resource_dns_cname_record_test.go
  internal/provider/resource_dns_mx_record_set_test.go
  internal/provider/resource_dns_ns_record_set_test.go
  internal/provider/resource_dns_ptr_record_test.go
  internal/provider/resource_dns_srv_record_set_test.go
  internal/provider/resource_dns_txt_record_set_test.go
Labels: size/L, technical-debt, tests
