Repository hashicorp/terraform-provider-dns, pull requests merged in 2023-05, with the labels that each got.

#301 provider: Ensure timeout configuration value is parsed correctly
  .changes/unreleased/BUG FIXES-20230501-131218.yaml
  internal/provider/provider_framework.go
  internal/provider/provider_framework_test.go
  internal/provider/provider_test.go
Labels: bug, size/L

#300 internal/provider: Migrate rest of acceptance testing from ProviderFactories to ProtoV5ProviderFactories
  internal/provider/provider_test.go
  internal/provider/resource_dns_a_record_set_test.go
  internal/provider/resource_dns_aaaa_record_set_test.go
Labels: size/XS, technical-debt

#304 fix: issue-labeler - add required input
  .github/workflows/issue-opened.yml
Labels: size/XS
