Repository hashicorp/terraform-provider-dns, pull requests merged in 2024-01, with the labels that each got.

#398 cdktf: update documentation
  docs/cdktf/python/data-sources/a_record_set.md
  docs/cdktf/python/data-sources/aaaa_record_set.md
  docs/cdktf/python/data-sources/cname_record_set.md
  docs/cdktf/python/data-sources/mx_record_set.md
  docs/cdktf/python/data-sources/ns_record_set.md
  docs/cdktf/python/data-sources/ptr_record_set.md
  docs/cdktf/python/data-sources/srv_record_set.md
  docs/cdktf/python/data-sources/txt_record_set.md
  docs/cdktf/python/index.md
  docs/cdktf/python/resources/a_record_set.md
  docs/cdktf/python/resources/aaaa_record_set.md
  docs/cdktf/python/resources/cname_record.md
  docs/cdktf/python/resources/mx_record_set.md
  docs/cdktf/python/resources/ns_record_set.md
  docs/cdktf/python/resources/ptr_record.md
  docs/cdktf/python/resources/srv_record_set.md
  docs/cdktf/python/resources/txt_record_set.md
  docs/cdktf/typescript/data-sources/a_record_set.md
  docs/cdktf/typescript/data-sources/aaaa_record_set.md
  docs/cdktf/typescript/data-sources/cname_record_set.md
  docs/cdktf/typescript/data-sources/mx_record_set.md
  docs/cdktf/typescript/data-sources/ns_record_set.md
  docs/cdktf/typescript/data-sources/ptr_record_set.md
  docs/cdktf/typescript/data-sources/srv_record_set.md
  docs/cdktf/typescript/data-sources/txt_record_set.md
  docs/cdktf/typescript/index.md
  docs/cdktf/typescript/resources/a_record_set.md
  docs/cdktf/typescript/resources/aaaa_record_set.md
  docs/cdktf/typescript/resources/cname_record.md
  docs/cdktf/typescript/resources/mx_record_set.md
  docs/cdktf/typescript/resources/ns_record_set.md
  docs/cdktf/typescript/resources/ptr_record.md
  docs/cdktf/typescript/resources/srv_record_set.md
  docs/cdktf/typescript/resources/txt_record_set.md
Labels: size/M

#399 Add `issues: write` permission to release workflow to close associated GitHub milestone
  .github/workflows/release.yml
Labels: size/XS

#402 cdktf: update documentation
  docs/cdktf/python/data-sources/a_record_set.md
  docs/cdktf/python/data-sources/aaaa_record_set.md
  docs/cdktf/python/data-sources/cname_record_set.md
  docs/cdktf/python/data-sources/mx_record_set.md
  docs/cdktf/python/data-sources/ns_record_set.md
  docs/cdktf/python/data-sources/ptr_record_set.md
  docs/cdktf/python/data-sources/srv_record_set.md
  docs/cdktf/python/data-sources/txt_record_set.md
  docs/cdktf/python/index.md
  docs/cdktf/python/resources/a_record_set.md
  docs/cdktf/python/resources/aaaa_record_set.md
  docs/cdktf/python/resources/cname_record.md
  docs/cdktf/python/resources/mx_record_set.md
  docs/cdktf/python/resources/ns_record_set.md
  docs/cdktf/python/resources/ptr_record.md
  docs/cdktf/python/resources/srv_record_set.md
  docs/cdktf/python/resources/txt_record_set.md
  docs/cdktf/typescript/data-sources/a_record_set.md
  docs/cdktf/typescript/data-sources/aaaa_record_set.md
  docs/cdktf/typescript/data-sources/cname_record_set.md
  docs/cdktf/typescript/data-sources/mx_record_set.md
  docs/cdktf/typescript/data-sources/ns_record_set.md
  docs/cdktf/typescript/data-sources/ptr_record_set.md
  docs/cdktf/typescript/data-sources/srv_record_set.md
  docs/cdktf/typescript/data-sources/txt_record_set.md
  docs/cdktf/typescript/index.md
  docs/cdktf/typescript/resources/a_record_set.md
  docs/cdktf/typescript/resources/aaaa_record_set.md
  docs/cdktf/typescript/resources/cname_record.md
  docs/cdktf/typescript/resources/mx_record_set.md
  docs/cdktf/typescript/resources/ns_record_set.md
  docs/cdktf/typescript/resources/ptr_record.md
  docs/cdktf/typescript/resources/srv_record_set.md
  docs/cdktf/typescript/resources/txt_record_set.md
Labels: size/M

#406 .github/workflows: Update to hashicorp/ghaction-terraform-provider-release@v3
  .github/workflows/release.yml
Labels: size/XS

#412 Added GHA dependabot config for managing hashicorp actions
  .github/dependabot.yml
Labels: dependencies, size/XS
